### ISSUE TITLE
Specify the requirement for Ruby 2.5

### ISSUE THREAD

**Issue by roivant-briandfoy** [toptal/codeowners-checker#50]
`codeowners-checker` uses `yield_self`, which requires Ruby 2.5. However, it happily installs under Ruby 2.4. 

```
$ ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
$ codeowners-checker check
/home/test-user/.gem/ruby/gems/codeowners-checker-1.0.1/lib/codeowners/checker/code_owners.rb:41:in `list': undefined method `yield_self' for []:Array (NoMethodError)
```

**Comment by mpapis** [comment]
@roivant-briandfoy could you provide a PR:

- fix ruby version restriction, OR:
- refactor code to work on ruby 2.4

We will be happy to apply fix either way.
